config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.i18n import i18n_patterns


admin.site.site_header = "Back admin"
admin.site.site_title = "Muhammadnurning sahifasi"
admin.site.index_title = "Welcome Aziz"

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('products.urls'))
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += debug_toolbar_urls()

users/urls.py
from django.urls import path
from .views import register, login_view, logout_view


app_name = 'users'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout')
]

templates/base.html
{% load i18n %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block nimadur %} {% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">{% trans "Navbar" %}</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">{% trans "Home" %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex mx-3" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            <div class="nav-item">
              {% if request.user.is_authenticated %} 
                <button class="btn btn-outline-primary">
                  <a href="{% url 'user_cart' %}">
                    <i class="bi bi-bag-check"></i>
                  </a>
                  
                </button>
                <a href="{% url 'users:logout' %}">
                  Logout
                </a>
               
              {% else %} 
                <a href="{% url 'users:login' %}">Login</a> 
              {% endif %}
            </div>
          </div>
        </div>
      </nav>

    {% block content %} {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  
    {% block jscode %} {% endblock %}

</body>

</html>